### ISSUE TITLE
you should ideally implement interface in class

### ISSUE THREAD

**Issue by championswimmer** [Armour/vue-typescript-admin-template#1]
https://github.com/Armour/vue-typescript-admin-template/blob/cf391543cfe23ec0bdda78edaf158cdb9c56923b/src/store/modules/user.ts#L14

I think instead of rewriting the property types again, we should do

```ts
interface IPerson {
  age: number
}

@Module({})
class Person extends VuexModule implements IPerson {
  age = 10 // <- tsc forces it because of this ^^^
}
```

**Comment by Armour** [comment]
Oh that's way better, thanks for letting me know that, will change it soon! :)

**Comment by Armour** [comment]
Thanks! @championswimmer
