### ISSUE TITLE
eslint error

### ISSUE THREAD

**Issue by Jesn** [Armour/vue-typescript-admin-template#10]
Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by Armour** [comment]
More details? Which platform? Which editor or IDE? Did you make sure you use the latest code with the .eslintrc in the code? Did you change anything? Minimal reproducible repo?

**Comment by Jesn** [comment]
> More details? Which platform? Which editor or IDE? Did you make sure you use the latest code with the .eslintrc in the code? Did you change anything? Minimal reproducible repo?

win10  vscode

**Comment by Armour** [comment]
Sorry, I don't have win 10 for now, is that still happen for the latest code? Hope someone also uses win 10 can answer this question.

**Comment by WalkeR321** [comment]
> Hope someone also uses win 10 can answer this question.

Win10 + VSCode
No problems

**Comment by Armour** [comment]
@Jesn Closed due to inactivity and possibly wrong report according to @WalkeR321
