### ISSUE TITLE
/vue-typescript-admin-template-minimal/node_modules/vuex/types"' has no exported member 'Dictionary'.

### ISSUE THREAD

**Issue by CHENJIAMIAN** [Armour/vue-typescript-admin-template#103]
![image](https://user-images.githubusercontent.com/20126997/69908451-c71a7700-1424-11ea-9587-8c687d84e385.png)

**Comment by CHENJIAMIAN** [comment]
ERROR in f:/GitHubRepository/vue-typescript-admin-template-minimal/src/views/login/index.vue 75:10 Module '"../../../../../GitHubRepository/vue-typescript-admin-template-minimal/node_modules/vuex/types"' has no exported member 'Dictionary'.

**Comment by CHENJIAMIAN** [comment]
解决办法：
    其实这个错误并不影响运行

在node_modules/vuex/types/index.d.ts中， 加入以下代码，

export interface Dictionary<T> {
  [key: string]: T;
}

重新npm run serve即可消除错误提示

**Comment by Armour** [comment]
Fixed.
