### ISSUE TITLE
编译速度很慢

### ISSUE THREAD

**Issue by CHENJIAMIAN** [Armour/vue-typescript-admin-template#104]
minimal对比其他master模板，编译速度慢很多，修改一下要编译好久才热更新上去

新手，暂时不知道如何优化，希望有人告诉我优化方法

**Comment by dnsritch** [comment]
// lintOnSave: process.env.NODE_ENV === 'development',
  lintOnSave: false,

把eslint的代码检查关闭会快很多，项目默认保存进行代码检查
在vue.config.js里面

**Comment by lubianniu** [comment]
@dnsritch  按照提供的方法试了。虽然有点效果，但是并不理想，经过N次测试，平均每次编辑time耗时5340ms。

**Comment by puzzle9** [comment]
linux 很快
```
[1] Webpack: Finished after 49.443 seconds.
[1] 
[1] 
[1]   App running at:
[1]   - Local:   http://localhost:9527/ 
[1]   - Network: http://192.168.11.176:9527/
```

**Comment by dnsritch** [comment]
https://github.com/Armour/vue-typescript-admin-template/issues/92#issuecomment-566818448
发现了一个优化方式

**Comment by dnsritch** [comment]
https://github.com/Armour/vue-typescript-admin-template/issues/92#issuecomment-566818448
发现了一个新的优化方式，可以提高 热更新 速度

**Comment by hyzx86** [comment]
试试 vscode+  docker   或者 vscode + wsl 4秒 编译，贼香

**Comment by Armour** [comment]
duplicated

**Comment by hyzx86** [comment]
貌似已经解决了



---原始邮件---
发件人: "Chong Guo"<notifications@github.com&gt;
发送时间: 2020年11月8日(周日) 上午10:57
收件人: "Armour/vue-typescript-admin-template"<vue-typescript-admin-template@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Tony Han"<huarui2219@qq.com&gt;;
主题: Re: [Armour/vue-typescript-admin-template] 编译速度很慢 (#104)




 
duplicated
