### ISSUE TITLE
你好， 我 fork 了这个项目， 然后移了更多的 vue-element-admin 页面过来，不知能不能合到你的这个项目中

### ISSUE THREAD

**Issue by runner-mei** [Armour/vue-typescript-admin-template#11]
你好， 我 fork 了这个项目， 然后移了更多的 vue-element-admin 页面过来，不知能不能合到你的这个项目中

https://github.com/runner-mei/vue-typescript-admin-template

**Comment by Armour** [comment]
看起来很棒 我正好打算以后慢慢把全部的vue-element-admin弄出来
你可以先pull下我最新的改动么 最近有几个push 稍微refactor了下code  
另外我看你用了eslint的config 很多改动都是和style有关的 这部分一般editor都可以自己调整出来 而且每个人喜欢用的eslint config也不一样 所以我推荐你先注释掉那几行对code有大改动的config然后在发PR 这样我可以清楚的看到真正的feature改动有哪里 我们先focus功能 之后可以单独弄个code style的改动
等你有时间弄好后发个PR到develop branch吧 我review下 谢谢啦！

**Comment by runner-mei** [comment]
好的， 我这几天都在改

**Comment by runner-mei** [comment]
是不是可建一个任务列表，然后我有空一个个的改过来
每次我改之前先领个任务，然后提交， 省得我们之前做重了

**Comment by kevinlvhsl** [comment]
页面一进来就会把所有js都下载，是什么原因？
![image](https://user-images.githubusercontent.com/10493838/53709644-4702b900-3e74-11e9-908a-becfa29c4411.png)

**Comment by ZurrTum** [comment]
@kevinlvhsl 你可以了解一下vue-cli：https://cli.vuejs.org/zh/guide/html-and-static-assets.html#prefetch
>\<link rel="preload"\> 是一种 resource hint，用来指定页面加载后很快会被用到的资源，所以在页面加载的过程中，我们希望在浏览器开始主体渲染之前尽早 preload。
默认情况下，一个 Vue CLI 应用会为所有初始化渲染需要的文件自动生成 preload 提示。

**Comment by kevinlvhsl** [comment]
@ZurrTum  了解了，谢谢

**Comment by Ghostdar** [comment]
@runner-mei @Armour 最近项目有接触到这个，也想参与迁移的工作，可以建个组件迁移的Todo List吗？方便管理。

**Comment by Armour** [comment]
@Ghostdar @runner-mei #39 #40 我创建了一些todo list 然后你们可以从这里pick 然后发PR :)
如果觉得某个任务太大可以在分开成多个小任务

**Comment by Armour** [comment]
@runner-mei 十分感谢你的贡献 你可以看看能不能把你的那个很大的PR分开分别对应上这些任务 这样会好code review很多

**Comment by Armour** [comment]
@runner-mei 我把style方面已经定下来了 然后create了一个full-features分支 以后全功能版本的就在这个上面开发了 这个issue我先close了
