### ISSUE TITLE
项目build:prod 放到nginx后起不来

### ISSUE THREAD

**Issue by csdnpeter** [Armour/vue-typescript-admin-template#110]
报错如下
![image](https://user-images.githubusercontent.com/37481528/70690068-d638d900-1cf0-11ea-8349-54b88f3580b6.png)

**Comment by csdnpeter** [comment]
yarn run serve 能正常起来

**Comment by ling7334** [comment]
nginx配置是啥?
看上去像是目录路径匹配不到，返回了默认`index.html`文件。
你放到哪个文件夹下，要修改`vue.config.js`里的`publicPath`

**Comment by csdnpeter** [comment]
不好意思，忘关了。nginx配置问题
