### ISSUE TITLE
[建议] 侧边栏不能实时显示bug

### ISSUE THREAD

**Issue by ChenMinc** [Armour/vue-typescript-admin-template#112]
### 问题
在[branch: minimal]中，构建完毕后，进入内页。侧边栏layout > sidebar模块中，路径对应的导航不能实时高亮显示，并且刷新后丢失高亮
### 原因
未能实施获取路径信息，并修改对应navMenu组件的当前选项
### 解决方法
在 src/layout/components/Sidebar/index.vue中
el-menu添加attr
```
:default-active="activeMenu"
```
添加js代码
```javascript
get activeMenu() {
    const route = this.$route
    const { meta, path } = route
    if (meta.activeMenu) {
      return meta.activeMenu
    }
    return path
  }
```
代码来源处，原版[vue-admin-template](https://github.com/PanJiaChen/vue-admin-template/blob/master/src/layout/components/Sidebar/index.vue)

**Comment by Armour** [comment]
欢迎贡献代码 如果您那边测试确定fix了 可以给我pull request 谢谢

**Comment by Armour** [comment]
Fixed.
