### ISSUE TITLE
怎么没有使用 vuex-class

### ISSUE THREAD

**Issue by push-over** [Armour/vue-typescript-admin-template#115]
我看项目中安装了 vuex-class 这个包但是确没有使用，是为什么呢？

**Comment by passioncsu** [comment]
因为留给你自己用啊, 业务场景难免需要用vuex, 提前安装好让你用

**Comment by push-over** [comment]
你确定吗？  它使用了vuex 只不过用的别的   并不是vuex-class  我想把这两种结合到一起使用  如果不去改作者源码的基础上 使用 vuex-class 必须要手动去初始化

**Comment by Armour** [comment]
可能只是忘了删 哈哈哈哈哈
