### ISSUE TITLE
yarn run lint, 提示typescript版本不对

### ISSUE THREAD

**Issue by tomatobybike** [Armour/vue-typescript-admin-template#121]
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.7.5

Please only submit bug reports when using the officially supported version
==========================================================
可是package.json 里 "typescript": "^3.7.5",

**Comment by Armour** [comment]
目前基本没发现什么影响 如果有发现影响请提出来 谢谢～
