### ISSUE TITLE
源码运行面包屑的”首页“点击会报错。

### ISSUE THREAD

**Issue by MichaelMa666** [Armour/vue-typescript-admin-template#127]
点击面包屑的首页，会报错`[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'compile' of undefined"`
![企业微信20200312023100](https://user-images.githubusercontent.com/17587845/76493750-5c8ac580-646e-11ea-8b9b-a35802b389da.png)

**暂时解决办法：**
修改文件src/components/Breadcrumb/index.vue第52行，增加`redirect: '/dashboard'`
![企业微信截图_912b8c7e-ac06-4da3-91f6-586281bbf8eb](https://user-images.githubusercontent.com/17587845/76494076-12eeaa80-646f-11ea-8c54-91ae27e53153.png)

不知道后续有没问题，看花裤衩的代码也是Armour这么写的，却不报错。有遇到一样问题的吗？

**Comment by shadowkimi520** [comment]
结论：和花裤衩用的pathToRegexp包的版本不一样，花裤衩的是2.4.0的，Armour的master分支用的6.1.0；
具体原因：
1. pathToRegexp这个包原先是commonjs模块规范的，最新的是es6模块规范的（最终的包代码里有包含Object.defineProperty(exports, "__esModule", { value: true });）
2. import pathToRegexp from 'path-to-regexp'  是es6默认导入，经过babel转译后大概是下面这样：
`var _pathToRegexp = _interopRequireDefault(require("pathToRegexp"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`
而且原先对pathToRegexp的访问会转成`_pathToRegexp.default`
3. v2.4.0的pathToRegexp包基于commonjs模块，没有__esModule属性，因此导入后为`_pathToRegexp = { default: module.exports }` 对象，`_pathToRegexp.default`能访问到最终导出的对象；v6.1.0的pathToRegexp包基于es6模块，有__esModule属性，`_pathToRegexp = module.exports` 所以 `_pathToRegexp.default` 为undefined，导致后续的compile属性访问报错

解决办法：
v6.1.0的版本compile函数不依附在pathToRegexp对象上，因此需要直接引入并使用，方法如下：
`import { compile } from 'path-to-regexp'`
然后把代码中的 pathToRegexp.compile 到换成 compile

**Comment by Armour** [comment]
Thanks for figuring this out, fixed in the latest version :) 

感谢 已修复
