### ISSUE TITLE
app-main Page transition

### ISSUE THREAD

**Issue by ZurrTum** [Armour/vue-typescript-admin-template#13]
# bug report

## Current behavior
跟 vue-element-admin 项目的页面过渡效果不一致，下方出现滚动条。

## Expected behavior
没有滚动条

## Minimal reproduction of the problem with instructions
登录 -> 点击侧边栏页面 (Form) -> 点击上方的 Dashboard
页面切换时会出现滚动条

## 修正方式
为 .app-main 添加 overflow:hidden;

来自 vue-element-admin 的 AppMain.vue
![code](https://user-images.githubusercontent.com/31088040/53692861-ecb11c00-3dd1-11e9-9f05-40a254c8cf8e.jpg)

**Comment by ZurrTum** [comment]
为什么删除呢？
https://github.com/Armour/vue-typescript-admin-template/commit/5448ddc91eef4b03ce3d686474db552e1e8ffb76#diff-2835501a98ef1814a5f8e839678fb77c

**Comment by Armour** [comment]
感谢提醒 之前想把sass清理一下 删掉一些可能不必要的地方 可能会有误删 你可以发个PR到develop分支或者等我改天加上
