### ISSUE TITLE
编译报错，看不出什么原因啊。。怎么能放出来呀？？

### ISSUE THREAD

**Issue by hyzx86** [Armour/vue-typescript-admin-template#135]
![image](https://user-images.githubusercontent.com/15613121/78680169-c1c2c100-791d-11ea-8efe-62951fccfa0c.png)

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/78680856-98eefb80-791e-11ea-907e-1bc887472303.png)

**Comment by Armour** [comment]
Now, this is removed, thanks :D
