### ISSUE TITLE
path直接访问/login或登录成功后访问/dashboard报404

### ISSUE THREAD

**Issue by Airpy** [Armour/vue-typescript-admin-template#14]
## 直接访问/login 404
在路由前置守卫(permission.ts)文件
`    if (whiteList.indexOf(to.path) !== -1) {
      next();
    }`
理应跳到登录页面，不知道为何404

## 登录成功后直接刷新页面404
router没有该路由

**Comment by Armour** [comment]
这是router history mode的[问题](https://stackoverflow.com/questions/47677220/vuejs-history-mode-with-github-gitlab-pages) 当deploy在GitHub pages时会有这个问题 你在本地试试是没问题的

fix的方法:

1. 本地是没问题的
2. deploy到github pages时 disable history mode 或者 尝试一些[hack](https://stackoverflow.com/questions/47677220/vuejs-history-mode-with-github-gitlab-pages/50259501#50259501)

**Comment by Armour** [comment]
我暂时disable了 现在好了
