### ISSUE TITLE
Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/guide/index") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int…node_modules/vue/dist/vue.runtime.esm.js:2178:14)"}

### ISSUE THREAD

**Issue by maozhenzhong** [Armour/vue-typescript-admin-template#140]
# I'm submitting a

![image](https://user-images.githubusercontent.com/11130699/81036368-74605200-8ed1-11ea-975f-8f65c6938aeb.png)
当标签只剩下首页和当前页的时候，右键点击关闭其他就会报错出现以下错误
Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/guide/index") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int…node_modules/vue/dist/vue.runtime.esm.js:2178:14)"}

## What is the motivation / use case for changing the behavior

修改方法
找到layout/components/TagsView/index.vue

private closeOthersTags() {
    if (this.selectedTag.fullPath !== undefined) {
      this.$router.push(this.selectedTag.fullPath)
    }
    TagsViewModule.delOthersViews(this.selectedTag)
    this.moveToCurrentTag()
  }

改为
private closeOthersTags() {
    if (this.selectedTag.fullPath !== this.$route.path && this.selectedTag.fullPath !== undefined) {
      this.$router.push(this.selectedTag.fullPath)
    }
    TagsViewModule.delOthersViews(this.selectedTag)
    this.moveToCurrentTag()
  }

也就是加上这条语句
this.selectedTag.fullPath !== this.$route.path 即可

**Comment by Armour** [comment]
你可以发一个PR 我帮你通过

**Comment by maozhenzhong** [comment]
> 你可以发一个PR 我帮你通过

提交了

**Comment by Armour** [comment]
#141
