### ISSUE TITLE
[Question] Why you don't use NUXT SPA mode for this?

### ISSUE THREAD

**Issue by harrytran998** [Armour/vue-typescript-admin-template#142]
Hi @Armour , my team prepare code a WEB for Admin like this. But we still confuse, should use VueCLI or Nuxt SPA mode? It's about the page's speed, or something?
Hope you can take some time for this question 💪.
Thank you

**Comment by Armour** [comment]
Sorry, I didn't use Nuxt often, I would recommend you google the difference for them.

**Comment by harrytran998** [comment]
Ok thank you 🔥
