### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by dongshihao666** [Armour/vue-typescript-admin-template#145]
<img width="905" alt="WechatIMG90" src="https://user-images.githubusercontent.com/29971202/83345027-f1e87800-a340-11ea-82fd-cd1c05171324.png">

**Comment by Armour** [comment]
Next time you can try to Baidu or Google it first, https://github.com/microsoft/TypeScript/issues/38535

Either fix typescript version to 3.8.3, or wait for the fix with next typescript release.

**Comment by yanjianming2005** [comment]
虽说是TS的问题，可是首次运行不成功，还是很让人觉得不好的，难道不能写个脚本每天跑一边吗？

**Comment by Armour** [comment]
I set the typescript version back to 3.8.3 now, this should be fixed. @yanjianming2005 @dongshihao666  Thanks :D
