### ISSUE TITLE
关于 store 中 actions 写法的疑问

### ISSUE THREAD

**Issue by Ucag** [Armour/vue-typescript-admin-template#149]
在代码中多处看到直接在 @Action 修饰符的方法下面直接调用 this.SET_MUTATION = xx 之类的语句, 难道不应该是在 Action 修饰符当中指出是 commit 哪一个 mutation 吗, 或者是使用 this.context 来commit 一个 mutation 吗? 
或者是我哪里没有注意到的细节?
--- 来自一个正在学习 vue ts admin 架构初学者提问.

**Comment by 329988300** [comment]
ts中是es6的class写法，class类中的方法之间调用，直接用this就可以获取到的吧
