### ISSUE TITLE
Redirected when going from "/login?redirect=%2Fdashboard" to "/dashboard"

### ISSUE THREAD

**Issue by wxbo22** [Armour/vue-typescript-admin-template#150]
场景：登录成功后，退出登录，再次登录就会报这个错，我看了参考demo也有这个问题，请教如何解决这个报错

**Comment by rcqcxy** [comment]
我也遇到了

**Comment by wxbo22** [comment]
这个问题无解么

**Comment by AJenpan** [comment]
you can fix that problem on the function `handleLogin `  at views/login/index.vue 
like:
```
          // this.$router.push({
          //   path: this.redirect || "/",
          //   query: this.otherQuery
          // });
          location.reload()
```

**Comment by zeigo** [comment]
可以参考这个
[1](https://github.com/PanJiaChen/vue-element-admin/issues/3243)
[2](https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378)
我的理解是，permission.ts里的`next({ ...to, replace: true })`会被认为是一个失败的navigation（虽然能导航成功，但不再是原来的to），所以login里的push()返回一个rejected Promise。
解决方案：在push()后面接一个.catch(()=>{})

**Comment by crazy-airhead** [comment]
也可参考这里的解决办法，https://github.com/PanJiaChen/vue-element-admin/issues/2764

**Comment by tnnevol** [comment]
动态添加路由后使用next({ replace: true })就会发生这样的错误，解决方案 改写成router.replace() 或者 使用.catch捕捉这个异常

**Comment by pan33** [comment]
> location.reload()

The solution of AJenpan is right.
