### ISSUE TITLE
ie浏览器白屏

### ISSUE THREAD

**Issue by dongshihao666** [Armour/vue-typescript-admin-template#159]
ie浏览器打开白屏 请问怎么解决呀
![WechatIMG1794](https://user-images.githubusercontent.com/29971202/89248840-4828ae80-d643-11ea-919c-962d37f33b75.jpeg)

**Comment by luanweijie** [comment]
+1

**Comment by luanweijie** [comment]
> ie浏览器打开白屏 请问怎么解决呀
> ![WechatIMG1794](https://user-images.githubusercontent.com/29971202/89248840-4828ae80-d643-11ea-919c-962d37f33b75.jpeg)

此问题是fuse.js库不兼容，
可以在vue.config.js里配置如下选项：
transpileDependencies: ['fuse.js'],

**Comment by Armour** [comment]
#148 duplicated

**Comment by lifuhai1106** [comment]
报错：引发了异常但未捕获
