### ISSUE TITLE
Cannot Login: Proxy error and ERR_ACTION_ACCESS_UNDEFINED

### ISSUE THREAD

**Issue by thaibm** [Armour/vue-typescript-admin-template#161]
# I'm submitting a Bug report
## Current behavior
I clone the new one, install and run serve. When I try to login on the page. I got this error:
1. Proxy error: Could not proxy request
2. Error: ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action?

![image](https://user-images.githubusercontent.com/5625757/89920551-bb738700-dc26-11ea-8067-b228a1d321eb.png)
![image](https://user-images.githubusercontent.com/5625757/89920861-258c2c00-dc27-11ea-9986-3a1fa8d07e94.png)

## Expected behavior
Can login without above error

## Minimal reproduction of the problem with instructions
Step: Clone new project -> npm install -> npm run serve -> Login

## Environment
MacOS 10.15

**Comment by Armour** [comment]
#114 duplicated, should be fixed now.
