### ISSUE TITLE
项目启动报错 2020-08-22

### ISSUE THREAD

**Issue by Zhongxiangyun** [Armour/vue-typescript-admin-template#162]
(node:6464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ concurrently "npm:mock" "vue-cli-service serve"
'concurrently' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Armour** [comment]
should be fixed.
