### ISSUE TITLE
A question regarding the copyright of default 404 image

### ISSUE THREAD

**Issue by tcdw** [Armour/vue-typescript-admin-template#198]
# I'm submitting a

...question regarding copyright issues of the default 404 image.

We are developing a commercial project under this template. However, I noticed there is an [image](https://github.com/Armour/vue-typescript-admin-template/blob/master/src/assets/404-images/404.png) claims "All rights reserved wallstreetcn" in the default 404 page.

We want to know if this image is safe to use in a commercial project. It's important to make sure we won't get into any trouble regarding copyright problems.

Thanks!

**Comment by Armour** [comment]
I would suggest you change the 404 image to your own, in that case it should be fine.

**Comment by tcdw** [comment]
Thanks for your reply! We will design our custom 404 page for the project.
