### ISSUE TITLE
没有开发环境和生产环境的配置，没有国际化，动态路由没实现，加油哇

### ISSUE THREAD

**Issue by zhangjinghuan** [Armour/vue-typescript-admin-template#2]

**Comment by zhangjinghuan** [comment]
运行环境我弄好了：
"serve-dev": "vue-cli-service serve",
    "serve-pro": "vue-cli-service serve --mode production",
    "build-dev": "vue-cli-service build",
    "build-pro": "vue-cli-service build --mode production",
这是我配置的，再把环境文件.evn,改为：.env.development 和.evn.production两个

**Comment by Armour** [comment]
如果是非typescript类的issue推荐提到 https://github.com/PanJiaChen/vue-admin-template 我这个是于vue-admin-template的一个typescript verstion copy 谢谢啦～
