### ISSUE TITLE
[Components] Editors

### ISSUE THREAD

**Issue by Armour** [Armour/vue-typescript-admin-template#20]
Migrate following components from [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)

- [ ] Rich Text Editor
- [ ] Markdown Editor
- [ ] JSON Editor

**Comment by runner-mei** [comment]
这个我来做

**Comment by runner-mei** [comment]
有别的事暂停了，有人接手就接吧

**Comment by Armour** [comment]
Done :)
