### ISSUE TITLE
[Components] Avatar Upload

### ISSUE THREAD

**Issue by Armour** [Armour/vue-typescript-admin-template#21]
Migrate Avatar Upload component from [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)

- [x] Avatar Upload

**Comment by runner-mei** [comment]
这个我来做

**Comment by runner-mei** [comment]
有别的事暂停了，有人接手就接吧

**Comment by Armour** [comment]
@terry-ice is working on this

**Comment by Armour** [comment]
Done.
