### ISSUE TITLE
打包报错了

### ISSUE THREAD

**Issue by cxf1112** [Armour/vue-typescript-admin-template#213]
OKAY  take it away `electron-builder`

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.8 appOutDir=build\win-unpacked
  • downloading     path=C:\Users\zjzl\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.6.1-x64 url=https://github.com/develar/app-builder/releases/download/v0.6.1/app-builder-v0.6.1-win-x64.7z
  • cannot download: Error: connect ETIMEDOUT 13.229.188.59:443 path=C:\Users\zjzl\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.6.1-x64 attempt=1
Error: connect ETIMEDOUT 13.229.188.59:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
From previous event:
    at CancellationToken.createPromise (F:\electron\electron-vue-admin-master\node_modules\builder-util-runtime\src\CancellationToken.ts:51:5)
    at F:\electron\electron-vue-admin-master\node_modules\builder-util\src\nodeHttpExecutor.ts:23:44
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:462:21)
From previous event:
    at NodeHttpExecutor.download (F:\electron\electron-vue-admin-master\node_modules\builder-util\out\nodeHttpExecutor.js:144:11)
    at Timeout._onTimeout (F:\electron\electron-vue-admin-master\node_modules\builder-util\src\binDownload.ts:83:14)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-admin@3.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vue-admin@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zjzl\AppData\Roaming\npm-cache\_logs\2021-07-06T07_33_58_304Z-debug.log

**Comment by 13250515751** [comment]
大佬，帮忙看一下什么问题？

**Comment by cxf1112** [comment]
> OKAY take it away `electron-builder`
> 
> • electron-builder version=19.56.2
> • loaded configuration file=package.json ("build" field)
> • writing effective config file=build\electron-builder.yaml
> • no native production dependencies
> • packaging platform=win32 arch=x64 electron=1.8.8 appOutDir=build\win-unpacked
> • downloading path=C:\Users\zjzl\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.6.1-x64 url=https://github.com/develar/app-builder/releases/download/v0.6.1/app-builder-v0.6.1-win-x64.7z
> • cannot download: Error: connect ETIMEDOUT 13.229.188.59:443 path=C:\Users\zjzl\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.6.1-x64 attempt=1
> Error: connect ETIMEDOUT 13.229.188.59:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
> From previous event:
> at CancellationToken.createPromise (F:\electron\electron-vue-admin-master\node_modules\builder-util-runtime\src\CancellationToken.ts:51:5)
> at F:\electron\electron-vue-admin-master\node_modules\builder-util\src\nodeHttpExecutor.ts:23:44
> at Generator.next ()
> at processImmediate (internal/timers.js:462:21)
> From previous event:
> at NodeHttpExecutor.download (F:\electron\electron-vue-admin-master\node_modules\builder-util\out\nodeHttpExecutor.js:144:11)
> at Timeout._onTimeout (F:\electron\electron-vue-admin-master\node_modules\builder-util\src\binDownload.ts:83:14)
> at listOnTimeout (internal/timers.js:555:17)
> at processTimers (internal/timers.js:498:7)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! electron-vue-admin@3.0.0 build: `node .electron-vue/build.js && electron-builder`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron-vue-admin@3.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\zjzl\AppData\Roaming\npm-cache_logs\2021-07-06T07_33_58_304Z-debug.log
