### ISSUE TITLE
能否改为采用vite呢？

### ISSUE THREAD

**Issue by ankisme** [Armour/vue-typescript-admin-template#218]
我自己试着把`vue-typescript-admin-template`的`minimal`分支改成采用[vite](https://cn.vitejs.dev/)，然后发现启动真的很快，秒启动

但我的前端知识很有限，对`sass`、`scss`处理不好，导致左侧导航面板的界面样式被我改坏了，而且现在还残留着不少css的警告

所以想问问`vue-typescript-admin-template`的`minimal`分支什么时候会采用[vite](https://cn.vitejs.dev/)呢？

**Comment by Armour** [comment]
在计划中 空闲下来肯定会搞的 今年有点忙hh

**Comment by ankisme** [comment]
好，比较期待
