### ISSUE TITLE
[Components] Back To top & Count To

### ISSUE THREAD

**Issue by Armour** [Armour/vue-typescript-admin-template#22]
Migrate following components from [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)

- [x] Back To Top
- [x] Count To

**Comment by runner-mei** [comment]
这个我来做

**Comment by runner-mei** [comment]
有别的事暂停了，有人接手就接吧

**Comment by terry-ice** [comment]
我来做吧，分配给我吧

**Comment by Armour** [comment]
好的

**Comment by terry-ice** [comment]
@Armour 我提交了back-to-top 的merge

**Comment by Armour** [comment]
Thanks for your contribution!
