### ISSUE TITLE
[Components] Drop Zone & Sticky

### ISSUE THREAD

**Issue by Armour** [Armour/vue-typescript-admin-template#24]
Migrate following components from [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)

- [x] Drop Zone
- [x] Sticky

**Comment by runner-mei** [comment]
这个我来做

**Comment by Armour** [comment]
The sticky component is ready, just need the display page now

**Comment by Armour** [comment]
Done, thanks! @terry-ice
