### ISSUE TITLE
我在引入  npm install -save @types/cesium后，出现错误Module parse failed: Unexpected character '#' (1:0)

### ISSUE THREAD

**Issue by zhangjinghuan** [Armour/vue-typescript-admin-template#3]
我在引入  npm install -save @types/cesium后，获取对象，启动服务
出现错误
 error  in ./node_modules/requirejs/bin/r.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| /**
|  * @license r.js 2.3.6 Copyright jQuery Foundation and other contributors.

 @ ./node_modules/cesium/index.js 5:16-36

应该是webpack识别不了#号，求解决方法。

**Comment by Armour** [comment]
请给一个可以复现错误的最小repo 谢谢

**Comment by zhangjinghuan** [comment]
<template>
  <div class="wscn-http404-container" id="cesiumContainer">
  </div>
</template>

**Comment by Armour** [comment]
给个repo吧。。。 这个代码贴的也太乱了。。

**Comment by zhangjinghuan** [comment]
![default](https://user-images.githubusercontent.com/39046509/47332250-4d587b80-d6b1-11e8-9018-e5893cdeefcf.png)

**Comment by zhangjinghuan** [comment]
``<template>
  <div class="wscn-http404-container" id="cesiumContainer">
  </div>
</template>

<script lang='ts'>
import { Component, Vue } from 'vue-property-decorator';
// 导入Cesium源码中的Viewer组件，注意这里是用的Viewer组件的方式加载，而不是加载整个Cesium
import {Viewer} from 'cesium'
import 'cesium/Source/Widgets/widgets.css'
// import Cesium from 'cesium'
// import widgets from 'cesium'
// 如何让Cesium知道静态资源在哪里的API
import {buildModuleUrl} from 'cesium'
export default {
  name: 'cesiumContainer',
  mounted: function() {
    // 设置静态资源目录
    buildModuleUrl.setBaseUrl('static/Cesium/')
    // 创建viewer实例
    new Viewer('cesiumContainer')
  },
  data() {
    return {
      viewer: {}
    }
  }
}

</script>

<style rel="stylesheet/scss" lang="scss" scoped>
</style>

**Comment by zhangjinghuan** [comment]
@Armour 总共几行代码  记得先npm install -save @types/cesium

**Comment by Armour** [comment]
给个repo吧。。。 你这个截图我不想手动打一遍。。 谢谢

**Comment by Armour** [comment]
Closed due to inactivity.
