### ISSUE TITLE
layout/components/AppMain.vue 里边的 router-view 再次出现了ID#app

### ISSUE THREAD

**Issue by renxiaomeng** [Armour/vue-typescript-admin-template#4]
![image](https://user-images.githubusercontent.com/8308372/49705592-71b8e900-fc5a-11e8-8129-162c845bf70f.png)
不仅出现了多个ID#app，并且也没有动画效果和 section class="app-main" 这个标签
![image](https://user-images.githubusercontent.com/8308372/49705612-96ad5c00-fc5a-11e8-8dc6-9702c584d1c9.png)
在 [PanJiaChen/vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) 这个项目中并没有这个问题

**Comment by artskin** [comment]
![image](https://user-images.githubusercontent.com/968022/50771992-347e6000-12c7-11e9-933d-acfc4107de8a.png)

我是这么处理的，main.ts文件里，h外边的小括号去掉就好了

**Comment by renxiaomeng** [comment]
@artskin  我这边经测试，这个小括号去不去都一样的
起初我把app.vue 中 TS部分删除即可，后来我发现，其他的vue页面引用的vue是通过vue-property-decorator
![qq 20190108094836](https://user-images.githubusercontent.com/8308372/50804810-9623e600-132a-11e9-899b-c33f77ac78ef.png)

而App.vue中 是 
![qq 20190108093634](https://user-images.githubusercontent.com/8308372/50804766-6d035580-132a-11e9-831f-a42ebf81bf9c.png)

修改成 vue-property-decorator 方式即可

**Comment by Armour** [comment]
Make sure it fix the bug and you can send a PR if you want :)

**Comment by Armour** [comment]
@renxiaomeng  @artskin  修好了 方法是加上@Compnent 修饰符 因为我们用的是vue-class-component， 需要前后保持统一 
Vue那个倒是无所谓 因为vue-property-decorator的vue也是直接import的原生的vue
具体可以看我上面给的链接
