### ISSUE TITLE
更多的后台功能集成 (欢迎PR)

### ISSUE THREAD

**Issue by Armour** [Armour/vue-typescript-admin-template#40]
大家好，我们打算开始逐渐把更多的后台功能从原来的 [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) project 迁移到这个 typescript 的版本中， 我创建了一系列的 issues 用来更好的更新进度。 欢迎任何developer参与贡献👏 只需要开始接任务时在对应的 issue 里说一声 防止大家花时间做了重复工作， 感谢！🎉

**Comment by Armour** [comment]
当然如果你做得快完成了一个feature 即使有人提前mark了任务你也可以发PR 防止block整体进度

**Comment by Armour** [comment]
感谢 @xiaojianbu @yin-shu @DWmister 的积极参与！ 现在已经完成了[快一半了](https://github.com/Armour/vue-typescript-admin-template/projects)

**Comment by Armour** [comment]
首页也完成了！ 好看了不少hhh

**Comment by Armour** [comment]
目前完成70%左右了 感谢大家的贡献

**Comment by Armour** [comment]
感谢 @terry-ice 的贡献 #22

**Comment by terry-ice** [comment]
@Armour 不客气，我后续会继续迁移一些组件过来，我也很喜欢这个项目，打算用来做博客的后台管理

**Comment by Armour** [comment]
@terry-ice #24 感谢

**Comment by Armour** [comment]
原版完成度99%了 后续会陆续跟着更新的

**Comment by xhye** [comment]
TagsView移过来呗 QAQ

**Comment by Armour** [comment]
> TagsView移过来呗 QAQ

有了吧？

**Comment by Armour** [comment]
忘了关这个了 之前已经完成了

**Comment by yin-shu** [comment]
> 忘了关这个了 之前已经完成了

哈喽，现在有什么其他的项目做没，想继续参与，要不要用vue3搞一版

**Comment by Armour** [comment]
#170
