### ISSUE TITLE
安装项目只能yarn不能用npm？

### ISSUE THREAD

**Issue by zhangaofei** [Armour/vue-typescript-admin-template#43]
安装项目只能yarn不能用npm？

**Comment by Armour** [comment]
都可以

**Comment by zhangaofei** [comment]
启动项目md上面yarn serve我用npm serve启动不了，能写一下npm启动的方式吗

**Comment by Armour** [comment]
npm run serve

**Comment by zhangaofei** [comment]
是我的node版本不够   
ERROR  You are using Node v6.10.2, but vue-cli-service requires Node >=8.
Please upgrade your Node version.
考虑到升级node版本影响其他项目，去安装yarn，结果相关连接都是404

**Comment by zhangaofei** [comment]
是我的node版本不够   
ERROR  You are using Node v6.10.2, but vue-cli-service requires Node >=8.
Please upgrade your Node version.
考虑到升级node版本影响其他项目，去安装yarn，结果相关连接都是404
