### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by chen-jiawei** [Armour/vue-typescript-admin-template#49]
安装依赖完成之后，启动项目显示已成功，但是访问项目路径的时候，浏览器的控制台输出 Uncaught ReferenceError: exports is not defined

**Comment by Armour** [comment]
应该不会有这个问题 确认下你的环境以及用的哪个分支的code 估计是本地环境配置问题或者不小心改了哪里 因为暂时没有收到类似的反馈

**Comment by Armour** [comment]
Closed due to inactivity and the lack of information.
