### ISSUE TITLE
npm的方式会报错

### ISSUE THREAD

**Issue by artskin** [Armour/vue-typescript-admin-template#5]
# 请问这个支持npm 吗

> 仓库clone 下来， `npm install`之后
执行 `npm run serve`会出现报错

![image](https://user-images.githubusercontent.com/968022/50130177-516ed700-02b7-11e9-85a4-e356c735481a.png)

**Comment by Armour** [comment]
稍等 我回家看看 应该是可以的 我改一下

**Comment by artskin** [comment]
![image](https://user-images.githubusercontent.com/968022/50130575-33a27180-02b9-11e9-9729-a66108920898.png)
好像是redirect声明的数据类型问题。
我改成any就好了，不知道会有其他影响吗

**Comment by Armour** [comment]
原则上typescript里要尽量减少any的使用 看error感觉应该是 string | string[] | undefined 不过type是不影响运行的 所以你先就用any也行 我等会儿会改这里

**Comment by Armour** [comment]
改好了 这个是因为vue-router最新release改了router.query的type导致的 先临时修复下 以后看看更新情况再改

**Comment by artskin** [comment]
> 改好了 这个是因为vue-router最新release改了router.query的type导致的 先临时修复下 以后看看更新情况再改

谢谢Armour
