### ISSUE TITLE
拉取master分支添加echart出错

### ISSUE THREAD

**Issue by zhangaofei** [Armour/vue-typescript-admin-template#54]
echart部分改为ts时报@Prop的参数错误没发现什么错误，如下图
![image](https://user-images.githubusercontent.com/24579249/57346174-1c88f100-7180-11e9-90af-6b831ecd6581.png)，
然后按照develop分支的写法添加echart，出现新的错误如下：
![image](https://user-images.githubusercontent.com/24579249/57346174-1c88f100-7180-11e9-90af-6b831ecd6581.png)
然后安装 case-sensitive-paths-webpack-plugin模块 错误没有改变

**Comment by Armour** [comment]
请给个最小可复现repo 谢谢 （不过echart不是已经加进develop分支了么 好像已经好用了我记得

**Comment by zhangaofei** [comment]
上面的第一个搞错了，下面是第一个图
![image](https://user-images.githubusercontent.com/24579249/57346297-886b5980-7180-11e9-97f0-f6ab5033fd88.png)

**Comment by Armour** [comment]
语法错误 
请搜索下@Prop看看其他地方怎么写的

**Comment by zhangaofei** [comment]
我是这么写的
@Prop({ default: 'chart' }) className: string
  @Prop({ default: '200px' }) width: string
  @Prop({ default: '200px' }) id: string
  @Prop({ default: '200px' }) height: string
你的是这么写的：
 @Prop({ default: 'chart' }) private className!: string
  @Prop({ default: 'chart' }) private id!: string
  @Prop({ default: '200px' }) private width!: string
  @Prop({ default: '200px' }) private height!: string
