### ISSUE TITLE
模块导入相关问题

### ISSUE THREAD

**Issue by light0x00** [Armour/vue-typescript-admin-template#55]
# I'm submitting a feature request

## Current behavior

在「vue文件A」中导入「vue文件B」时,
如果B中把ts代码抽为一个单独文件,会导致A导入B时,typescript语法检查阶段报”B is not a module" (虽然不影响实际编译)

## Expected behavior

当然是不报红线啦(强迫症看着难受😅)

## Minimal reproduction of the problem with instructions

A.vue引入B.vue
```vue
<template>
</template>
<script lang="ts">
//! 检查阶段这里报 ”b.vue is not a module" 
import Comp2 from './b.vue' 
export default {}
</script>
```

B.vue引入单独的ts

```vue
<template>
</template>
<script src="./b.ts" lang="ts"></script>
```

## What is the motivation / use case for changing the behavior

如下,如果把B.vue的ts放在一起(而不是引入单独的ts文件),此时A.vue的导入就恢复正常了

B.vue

```vue
<template>
</template>
<script lang="ts">
export default {}
</script>
```

## Environment

system version: osx
ide: vscode
package manager: npm
typescript:3.3.4000

**Comment by Armour** [comment]
所以听起来不是个bug 只是逼死强迫症？🤣 什么情况下你会prefer用这种写法呢？
```typescript
<script src="./b.ts" lang="ts"></script>
```

这样行不行：
```typescript
<script lang="ts">
import './b.ts'

// blahblah..
</script>
```

**Comment by light0x00** [comment]
> 所以听起来不是个bug 只是逼死强迫症？🤣 什么情况下你会prefer用这种写法呢？
> 
> ```ts
> <script src="./b.ts" lang="ts"></script>
> ```
> 
> 这样行不行：
> 
> ```ts
> <script lang="ts">
> import './b.ts'
> 
> // blahblah..
> </script>
> ```

这样没问题啊! 我已经妥协了改回这样了. 谢谢答复. 感觉还是typescript对vue的支持不好哇. 这样的话我就把问题关啦
