### ISSUE TITLE
ERR_ACTION_ACCESS_UNDEFINED

### ISSUE THREAD

**Issue by herosPan** [Armour/vue-typescript-admin-template#6]
index.js?6fc5:318 Uncaught (in promise) Error: ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action?
That works only in dynamic modules.
If not dynamic use this.context.commit("mutationName", payload) and this.context.getters[“getterName”]
Error: Could not perform action Login

![qq 20181220102604](https://user-images.githubusercontent.com/39436000/50264806-55395f80-0457-11e9-9add-caf4fd887190.png)
![qq 20181220102623](https://user-images.githubusercontent.com/39436000/50264807-579bb980-0457-11e9-9660-223b7b114852.png)
![qq 20181220102510](https://user-images.githubusercontent.com/39436000/50264810-59657d00-0457-11e9-9805-66665e3d06a3.png)

**Comment by herosPan** [comment]
知道这是什么原因吗

**Comment by happynessTony** [comment]
这是怎么导致的? 我遇到了相同的问题 发现module内 throw Error(...) 就会报错

**Comment by dnsritch** [comment]
这是一个bug，vuex-module-decorator 默认会包装 module 里的错误，把原来的错误替换掉了
https://github.com/championswimmer/vuex-module-decorators/issues/86
