### ISSUE TITLE
请教一个问题：在401.vue文件中import 静态文件语法错，导致build不过

### ISSUE THREAD

**Issue by Airpy** [Armour/vue-typescript-admin-template#61]
```js
import errGif from "@/assets/401_images/401.gif";
```
这行，我在npm run build的时候，提示找不到对应的文件，静态文件没有export能import xxx from？？

**Comment by Armour** [comment]
可以的 https://armour.github.io/vue-typescript-admin-template/#/error/401

**Comment by Airpy** [comment]
您好，我是想问的，import xxx from
“@/xxx/xxx.gif”，这样的引入方式，是需要有什么配置吗？我这边的工程这样的方式引入，build的时候发现找不到gif文件

Chong Guo <notifications@github.com> 于2019年5月26日周日 上午2:31写道：

**Comment by Armour** [comment]
vue-cli 默认自带的image import配置是这样的：

```
...
      /* config.module.rule('images') */
      {
        test: /\.(png|jpe?g|gif|webp)(\?.*)?$/,
        use: [
          /* config.module.rule('images').use('url-loader') */
          {
            loader: 'url-loader',
            options: {
              limit: 4096,
              fallback: {
                loader: 'file-loader',
                options: {
                  name: 'img/[name].[hash:8].[ext]'
                }
              }
            }
          }
        ]
      },
...
```

`file-loader` 一般都是可以的 其次你要确定下你的代码 1.支不支持import （es6） 2.路径对不对（是不是解析有问题 没找到正确路径）

**Comment by Armour** [comment]
对于我这个项目用的vue-cli自动生成的config 你试试 `vue inspect` 会打印出webpack的配置详情

**Comment by Armour** [comment]
另外几点：

1. @的解析
```
resolve: {
    alias: {
      '@': '/Users/chongguo/Github/vue-typescript-admin-template/src',
      vue$: 'vue/dist/vue.runtime.esm.js'
    },
}
```

2. gif type definition
https://github.com/Armour/vue-typescript-admin-template/blob/19c32b0095b35be6267ee51da7b92ae536743198/src/shims-vue.d.ts#L10

**Comment by Airpy** [comment]
感谢，解释很详细，但对于我这个vue新手确实难度不小。您刚提到的几处配置我都是vue/cli默认的，暂没做任何改动

Chong Guo <notifications@github.com> 于2019年5月26日周日 上午11:58写道：

**Comment by Armour** [comment]
一般这种问题最好给个可复现的最小例子 比如你的GitHub repo

**Comment by Armour** [comment]
如果你完全没有改的话 理论上应该不会发生这样的问题 只可能是环境的问题了 比如操作系统 npm版本 等等

**Comment by Airpy** [comment]
谢谢您的耐心解答。目前我的项目主体框架是用的你的develop分支的代码，src目录下的大部分都是复用您的，除去views同级的几个配置文件目前我还没拷贝至项目中，如vue.config.js等文件，因为很多配置不知道具体的使用场景，哎。

对了，您有微信或者qq交流群吗，针对于这个项目。

Chong Guo <notifications@github.com> 于2019年5月26日周日 下午12:30写道：

**Comment by Armour** [comment]
emm 因为这是我去年年底才开始写的项目 所以暂时没有群 不过我正打算建一个 我现在建吧 然后我会尽量回答大家的问题 之后也会更新一波typescript版本的文档的

**Comment by Armour** [comment]
![image](https://user-images.githubusercontent.com/5276065/58377562-9cf97100-7f38-11e9-8f94-1ce61eae541b.png)

先用这个吧 我随便拉了几个朋友hh

**Comment by Armour** [comment]
暂时先关了 可以群里讨论

**Comment by ty793941** [comment]
二维码已过期，能否再给一下

**Comment by Armour** [comment]
> 二维码已过期，能否再给一下

https://github.com/Armour/vue-typescript-admin-template/issues/62
