### ISSUE TITLE
Material Design input not editable

### ISSUE THREAD

**Issue by fosk06** [Armour/vue-typescript-admin-template#67]
The MaterialInput in the mixin vue is not editable.
You can not set any value inside it, wich is a bit weird for an input.
It's also present on the demo [website](https://armour.github.io/vue-typescript-admin-template/#/components/mixin) 
the compnent is located here : src/views/components-demo/mixin.vue

 node -v -> v12.4.0

**Comment by Armour** [comment]
ok, I’ll take a look. Thanks for the feedback!

**Comment by Armour** [comment]
Fixed.

Reason: “maxlength” for input default set to 0. Change it to other default value will fix this bug.

I'll push this fix to master branch soon.
