### ISSUE TITLE
开发的时候编译慢

### ISSUE THREAD

**Issue by cjz9032** [Armour/vue-typescript-admin-template#68]
[1]  DONE  Compiled successfully in 18193ms11:51:49
[1]
[1] No type errors found
[1] Version: typescript 3.5.2
[1] Time: 12408ms
为啥修改一个要这么慢,10s-20s

**Comment by tyzero** [comment]
重新编译10几秒正常呀，而且基本上可以hot-load，没事重新编译干啥呢

**Comment by Armour** [comment]
是hot-reload慢么 还是？ hot-reload慢的话 我可以最近找时间研究研究

**Comment by cjz9032** [comment]
> 是hot-reload慢么 还是？ hot-reload慢的话 我可以最近找时间研究研究

是hot-reload，i7的pc，测试过2台机器都如此。
想跟进各个模块看统计时间，发现还要跟到源码，暂时就没看了。

**Comment by Armour** [comment]
好 我找时间看看

**Comment by Armour** [comment]
@cjz9032 你再试试 现在应该快不少 估计平均只要2-5s？

**Comment by Armour** [comment]
@cjz9032 如果没什么别的问题就自己关掉这个issue吧

**Comment by cjz9032** [comment]
> @cjz9032 如果没什么别的问题就自己关掉这个issue吧

三克油,因为太匆忙了,一直没看到这里~~~
