### ISSUE TITLE
使用路由懒加载后，打包部署到服务器，页面显示白屏

### ISSUE THREAD

**Issue by will0428** [Armour/vue-typescript-admin-template#7]
## 问题来源  
使用了[vue+ts的脚手架](https://github.com/ws456999/vue-typescript-starter)，在router/index.js中更改为路由懒加载的写法，npm run dev页面正常显示；npm run build打包后部署到服务器，首页白屏，无法正常显示，无报错信息。
## 验证的相关信息  
[ts项目增加路由懒加载后白屏](https://segmentfault.com/q/1010000017482172)    
上面的脚手架中，将router/index.ts中的改成路由懒加载写法，并在config/index，build下的assetsPublicPath，由/改为./后即可验证  
作者大大，我看你项目中使用了路由懒加载，请教下上面的问题。。。。

**Comment by Armour** [comment]
Did you change the [baseurl](https://cli.vuejs.org/config/#baseurl) for vue-cli? The default production baseurl in my project is ['vue-typescript-admin-template'](https://github.com/Armour/vue-typescript-admin-template/blob/master/vue.config.js) and you should change it to ""(empty string) if you just want to test the production build without url sub-path.

**Comment by will0428** [comment]
Your project is based on vue-cli 3? My project is based on vue-cli 2,and I change  assetsPublicPath from '/' to './' that is the same effect as you mean.However it doesn't work.  
My problem is that if I add Lazy Loading Routes in [my project](https://github.com/ws456999/vue-typescript-starter),it show nothing when I test production build.    
┭┮﹏┭┮，that problem troubled me for a long time

**Comment by Armour** [comment]
Close as this is not a bug for this project.
