### ISSUE TITLE
请问一下怎么在permission.ts模块中使用全局提示？

### ISSUE THREAD

**Issue by wzm-Bob** [Armour/vue-typescript-admin-template#72]
我在shims-vue.d.ts中声明了 iview的$Message  在vue中使用用正常，但在store的permission模块中过滤权限路由时  我需要提示以及路由跳转  ，如何才能使用$Message呢   this也只是指向模块或者window

**Comment by Armour** [comment]
看你已经在群里讨论过了？ 是不是可以关了呢 以及你把解决方案可以简单写出来

**Comment by Armour** [comment]
Closed due to inactivity.

**Comment by Jack-cool** [comment]
> 看你已经在群里讨论过了？ 是不是可以关了呢 以及你把解决方案可以简单写出来

大佬，友交流群吗

**Comment by didier1920** [comment]
亲，你肯定发错了人。。。
