### ISSUE TITLE
 Cypress App could not be downloaded

### ISSUE THREAD

**Issue by xieze** [Armour/vue-typescript-admin-template#73]
✖  Downloading Cypress    
   → Cypress Version: 3.4.0
    Unzipping Cypress      
    Finishing Installation 
The Cypress App could not be downloaded.

Please check network connectivity and try again:

----------

URL: https://cdn.npm.taobao.org/dist/cypress/3.4.0/osx64/cypress.zip
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: darwin (18.6.0)
Cypress Version: 3.4.0
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node index.js --exec install" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node index.js --exec install" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/_runscript@1.3.0@runscript/index.js:74:21)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by xieze** [comment]
i use "cnpm i" initialization，and then get this error

**Comment by Armour** [comment]
Try npm or yarn instead, it should work.

**Comment by Armour** [comment]
Removed cypress support now.
