### ISSUE TITLE
import express from 'express'报错

### ISSUE THREAD

**Issue by twins49** [Armour/vue-typescript-admin-template#79]
您好Armour，我是参考您的项目来改的 我在做mock服务那部分 我用了您的代码 做了部分修改
但是启动node服务的时候报错了
[mock] import express from 'express';
[mock]        ^^^^^^^
[mock] 
[mock] SyntaxError: Unexpected identifier
[mock]     at Module._compile (internal/modules/cjs/loader.js:721:23)
[mock]     at Module._compile (/home/twins49/youmi_project/opr/front_ui/node_modules/source-map-support/source-map-support.js:521:25)
[mock]     at Module.m._compile (/tmp/ts-node-dev-hook-21227122230772455.js:56:25)
[mock]     at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[mock]     at require.extensions.(anonymous function) (/tmp/ts-node-dev-hook-21227122230772455.js:58:14)
[mock]     at Object.nodeDevHook [as .ts] (/home/twins49/youmi_project/opr/front_ui/node_modules/ts-node-dev/lib/hook.js:61:7)
[mock]     at Module.load (internal/modules/cjs/loader.js:653:32)
[mock]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[mock]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[mock]     at Module.require (internal/modules/cjs/loader.js:690:17)
[mock] [ERROR] 14:35:00 SyntaxError: Unexpected identifier

**Comment by Armour** [comment]
我记得我群里回复过你了

**Comment by Armour** [comment]
Closed due to inactivity.

**Comment by lizi-fighting** [comment]
我也遇到了这个问题，能否提供一下解决方法？
