### ISSUE TITLE
如何按需加载element

### ISSUE THREAD

**Issue by H-Sven** [Armour/vue-typescript-admin-template#81]
```
import { Button, Message } from 'element-ui'
Vue.use(Button)
Vue.prototype.$message = Message
```

这样在ts版本下无法获取到 this..$message  这样  使用<el-button></el-button>也是一样提示要你注册

已经引入了 ```babel-plugin-component```   请问在ts中怎么按需加载  以及怎么想js版本一样使用Vue.prototype.扩展

**Comment by allfornaruto** [comment]
1.新建types/vue.d.ts
`
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface Vue {
    $message: any
  }
}
`
2.babel.config.js
`
module.exports = {
  presets: [
    '@vue/app',
    ["@babel/preset-env", { "modules": false }]
  ],
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
};
`
main.ts
`
import {Tabs,,Message} from "element-ui";
import Vue from "vue";

Vue.use(Tabs);
Vue.prototype.$message = Message;
`
