### ISSUE TITLE
vue-typescript-admin-template+spring boot

### ISSUE THREAD

**Issue by zhangpengyue1985** [Armour/vue-typescript-admin-template#86]
大佬，我现在在学习咱们这套前端，我想打包到spring boot中，怎么办，我在网上找了一些例子，都没实现。

**Comment by Armour** [comment]
群里问问？ 我暂时也没涉及过这方面

**Comment by enderjo** [comment]
前端打包的文件放到spring boot的静态资源目录即可（默订/resources/static）,要修改可以看下Spring boot的文档。
