### ISSUE TITLE
项目登录失败 Request failed with status code 500

### ISSUE THREAD

**Issue by hluglk** [Armour/vue-typescript-admin-template#88]
<img width="858" alt="截屏2019-10-11下午3 33 27" src="https://user-images.githubusercontent.com/11015416/66633053-7e241e80-ec3c-11e9-9168-76f0855e35d0.png">
<img width="1348" alt="截屏2019-10-11下午3 35 26" src="https://user-images.githubusercontent.com/11015416/66633165-c6dbd780-ec3c-11e9-8fb9-b130088370ee.png">

**Comment by victorwang0526** [comment]
我第一次也碰到这个问题，不过刷新一下，就又好了。暂时没仔细看什么情况。

**Comment by hluglk** [comment]
什么都没做又可以了
