### ISSUE TITLE
UserModule.GetInfo()始终执行then

### ISSUE THREAD

**Issue by tohkinzhu** [Armour/vue-typescript-admin-template#9]
permission.ts下
UserModule.GetInfo().then(() => {
          next();
        }).catch((err) => {
          //不会进入此处
        });
GetInfo里抛出异常，不会进入catch，始终是在then函数里。
浏览器log Could not perform action GetInfo。
不知道是不是只有我这样？捣鼓了一天没有解决掉。

**Comment by Armour** [comment]
不是很清楚具体什么情况 是哪儿报的错误？ 每次都发生么还是？ 需要具体信息 可能是有些环境配置不一样
另外我更新了些代码 你可以重新跑跑

**Comment by tohkinzhu** [comment]
额，就是UserModule.GetInfo()方法没法catch到，你在里面throw一个异常看看。
UserModule.GetInfo()..catch((err) => {
//不会进入此处
});
我现在改成了 try{

}catch(){
}

**Comment by Armour** [comment]
如果你觉得是个fix的话可以发个PR

**Comment by tohkinzhu** [comment]
好的 回头有空我弄下 我先关了
