### ISSUE TITLE
when yarn install packages can not continue

### ISSUE THREAD

**Issue by xiuyangzhe** [Armour/vue-typescript-admin-template#90]
[4/4] Building fresh packages...
[-/4] ⠐ waiting...
[2/4] ⠐ cypress
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...

always like that，can not continue(就是yarn 安装进行不下去最后一步)

**Comment by Armour** [comment]
关于 yarn 的安装问题 推荐网上搜索了解一下 大部分情况是因为墙的问题 如果不是很稳定的话 npm 和 yarn 可以考虑换着试试 因为这个并不是一个bug 所以先close了

**Comment by hyzx86** [comment]
同样的问题。。cypress 是没被镜像收录么？

**Comment by hyzx86** [comment]
解决了 先 npm install  开始 下载 cypress 的时候中断掉 ，然后 cnpm install  完美解决
