### ISSUE TITLE
代理错误 run serve 后登录报500错误

### ISSUE THREAD

**Issue by Raincoolly** [Armour/vue-typescript-admin-template#93]
好像是后台node，没跑起来，mock接口/ login 登录不了？

**Comment by czh50501607** [comment]
我也出现了同样的问题。我的系统是Mac OS
但mock的端口9528确实开了
你试试把vue.config里面的proxy.target替换 localhost 为 127.0.0.1，我能可以

**Comment by Armour** [comment]
麻烦确认下只开了一个实例 kill掉之前开的 不然有冲突会连不上

**Comment by shuiRong** [comment]
好像是vue.config.js的proxy的问题，我也遇到了。
解决方法是，修改request.ts里的baseURL为：`baseURL: 'http://localhost:9528/mock-api/v1',`

**Comment by Chesterton14** [comment]
登录404，同上面说到，把`baseURL`改为`http://localhost:9528/mock-api/v1`解决，尝试过在env环境文件里修改无效

**Comment by Armour** [comment]
其实好奇具体原因是什么 为啥proxy会不好用 0.0 是有什么别的问题导致node没跑起来吗 因为我本地无法reproduce这个问题

**Comment by Armour** [comment]
先close了 暂时无法复现
