### ISSUE TITLE
登录后控制台报错

### ISSUE THREAD

**Issue by mongoking** [Armour/vue-typescript-admin-template#94]
大佬有空时帮忙看看呗
拉取了master分支最新的代码
登录后控制台会打印个错误：vue-router.esm.js?8c4f:2051 Uncaught (in promise) undefined
不过不影响功能正常使用
就是感觉感觉不是太好 找了半天也没找到错误在哪里

**Comment by enderjo** [comment]
看这里https://github.com/vuejs/vue-router/issues/2881

**Comment by mongoking** [comment]
thanks
