### ISSUE TITLE
yarn install 错误 无法访问 69.63.178.13  npm install 可以

### ISSUE THREAD

**Issue by hliuug** [Armour/vue-typescript-admin-template#95]
Yarn version: 
  1.19.1

Node version: 
  12.13.0

Platform: 
  win32 x64

Trace: 
  Error: connect ETIMEDOUT 69.63.178.13:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)

**Comment by Armour** [comment]
这是 yarn vs npm 在你网络环境和配置下的问题 与此repo的代码没有直接联系 可以网上搜搜yarn为啥不好用 是不是要开代理翻q等等
